### ISSUE TITLE
Not enough cowbell

### ISSUE THREAD

**Issue by benjibee** [lukesmmr/rocket-reloaded#1]
Needs more cowbell! :+1:

**Comment by benjibee** [comment]
Reference: https://vimeo.com/55624839

**Comment by benjibee** [comment]
Original: https://www.youtube.com/watch?v=AUO_5EALZoM

**Comment by benjibee** [comment]
Further study: http://en.wikipedia.org/wiki/More_cowbell

**Comment by lukesmmr** [comment]
Definitely needs more cowbell!
